package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Build102'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Build102")
    name = "Build #102"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        script {
            name = "Print build number"
            scriptContent = "echo Hello from build 99"
        }
    }

    triggers {
        vcs {
        }
    }
}))

